import type { InstrumentKind } from "@/domain/catalog";

export type SeedInstrument = {
  id: string;
  kind: InstrumentKind;
  title: string;
  citation: string;
  articleRef?: string;
  summary: string;
  body: string;
  topics: string;
  tags: string;
  jurisdiction: string;
  locale: string;
  enactedYear?: number;
  status?: string;
  source: string;
  parentId?: string;
};

export const LEGAL_CORPUS: SeedInstrument[] = [
  {
    id: "in-const",
    kind: "CONSTITUTION",
    title: "Constitution of India",
    citation: "Constitution of India, 1950",
    summary:
      "India’s supreme law. It constitutes the Union, distributes power, and guarantees fundamental rights that ordinary statutes cannot abridge.",
    body: "The Constitution of India came into force on 26 January 1950. It is lengthy, federal with a strong Union, and justiciable. Part III (fundamental rights) and Part IV (directive principles) structure the relationship between citizen and State. Constitutional amendments follow Article 368; some changes also need ratification by States. Courts, especially the Supreme Court, interpret the text and have held that the “basic structure” cannot be destroyed by amendment.",
    topics: "constitution,federalism,fundamental rights,amendment",
    tags: "india,supreme law,article 368",
    jurisdiction: "IN",
    locale: "en",
    enactedYear: 1950,
    source: "Public constitutional text (educational abridgement)",
  },
  {
    id: "in-art-14",
    kind: "CONSTITUTION",
    title: "Article 14 — Equality before law",
    citation: "Constitution of India, Art. 14",
    articleRef: "Art. 14",
    parentId: "in-const",
    summary: "The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.",
    body: "Article 14 has two limbs: equality before the law (no special privilege) and equal protection (like should be treated alike). Reasonable classification is allowed if it is based on an intelligible differentia and a rational nexus with the object of the law. Arbitrary State action can be struck down. It applies to “any person”, not only citizens.",
    topics: "equality,discrimination,administrative law",
    tags: "article 14,fundamental rights",
    jurisdiction: "IN",
    locale: "en",
    enactedYear: 1950,
    source: "Constitution of India",
  },
  {
    id: "in-art-21",
    kind: "CONSTITUTION",
    title: "Article 21 — Protection of life and personal liberty",
    citation: "Constitution of India, Art. 21",
    articleRef: "Art. 21",
    parentId: "in-const",
    summary: "No person shall be deprived of life or personal liberty except according to procedure established by law.",
    body: "Article 21 is the workhorse of Indian rights jurisprudence. “Procedure established by law” has been read to require a fair, just and reasonable procedure (Maneka Gandhi). “Life” includes dignity, livelihood, privacy, health, and a clean environment as developed in later cases. Deprivation must still rest on a valid law.",
    topics: "liberty,privacy,due process,dignity",
    tags: "article 21,maneka gandhi",
    jurisdiction: "IN",
    locale: "en",
    enactedYear: 1950,
    source: "Constitution of India",
  },
  {
    id: "in-art-21-hi",
    kind: "CONSTITUTION",
    title: "अनुच्छेद 21 — प्राण और दैहिक स्वतंत्रता",
    citation: "भारत का संविधान, अनुच्छेद 21",
    articleRef: "अनुच्छेद 21",
    parentId: "in-const",
    summary: "किसी व्यक्ति को उसके प्राण या दैहिक स्वतंत्रता से विधि द्वारा स्थापित प्रक्रिया के अनुसार ही वंचित किया जा सकता है।",
    body: "अनुच्छेद 21 भारतीय अधिकार-विधि का केंद्र है। “विधि द्वारा स्थापित प्रक्रिया” को न्यायोचित, उचित और युक्तियुक्त होना चाहिए। “प्राण” में गरिमा, आजीविका, निजता और स्वास्थ्य जैसे पहलू भी न्यायिक व्याख्या से जुड़े हैं। यह पाठ शैक्षिक सार है; न्यायालय के समक्ष मूल पाठ देखें।",
    topics: "स्वतंत्रता,निजता,गरिमा",
    tags: "अनुच्छेद 21,संविधान",
    jurisdiction: "IN",
    locale: "hi",
    enactedYear: 1950,
    source: "भारत का संविधान (शैक्षिक सार)",
  },
  {
    id: "in-42nd",
    kind: "AMENDMENT",
    title: "Constitution (Forty-second Amendment) Act, 1976",
    citation: "42nd Amendment, 1976",
    parentId: "in-const",
    summary:
      "A wide-ranging amendment that altered the Preamble (Socialist, Secular, Integrity), expanded Directive Principles, and attempted to reduce judicial review — later partly rolled back.",
    body: "The 42nd Amendment is often called the “mini-constitution”. It inserted Socialist, Secular and Integrity in the Preamble, added duties of citizens, and tried to immunise constitutional amendments from judicial review. The 44th Amendment (1978) restored several civil-liberty protections. When researching “amendments to the Indian Constitution”, always read 42nd and 44th together.",
    topics: "amendment,preamble,emergency,judicial review",
    tags: "42nd,mini constitution",
    jurisdiction: "IN",
    locale: "en",
    enactedYear: 1976,
    source: "Constitution (Amendment) Acts",
  },
  {
    id: "in-44th",
    kind: "AMENDMENT",
    title: "Constitution (Forty-fourth Amendment) Act, 1978",
    citation: "44th Amendment, 1978",
    parentId: "in-const",
    summary: "Restored safeguards after the Emergency, including tightening Article 352 and protecting the essence of Articles 20 and 21 from easy suspension.",
    body: "The 44th Amendment responded to Emergency-era excesses. It made national emergency harder to proclaim, restored some property-related adjustments, and ensured that Articles 20 and 21 could not be suspended even during emergency. It is a key amendment for liberty research in India.",
    topics: "emergency,liberty,amendment",
    tags: "44th amendment,article 21",
    jurisdiction: "IN",
    locale: "en",
    enactedYear: 1978,
    source: "Constitution (Amendment) Acts",
  },
  {
    id: "in-cpc",
    kind: "STATUTE",
    title: "Code of Civil Procedure, 1908",
    citation: "CPC, 1908",
    summary: "The procedural code for civil suits in India: institution, pleadings, interim orders, trial, and execution of decrees.",
    body: "The CPC does not create rights; it channels how private-law rights are enforced. Order XXXIX covers temporary injunctions; Section 9 confers jurisdiction on civil courts unless barred. Limitation is governed mainly by the Limitation Act, 1963, read with the CPC. Parties should identify the correct court (pecuniary and territorial) before filing.",
    topics: "civil procedure,injunction,jurisdiction,suits",
    tags: "CPC,civil court",
    jurisdiction: "IN",
    locale: "en",
    enactedYear: 1908,
    source: "Acts of Parliament (educational abridgement)",
  },
  {
    id: "in-ica",
    kind: "STATUTE",
    title: "Indian Contract Act, 1872",
    citation: "ICA, 1872",
    summary: "Governs formation, performance, and breach of contracts: offer, acceptance, consideration, capacity, free consent, and remedies including damages.",
    body: "A contract is an agreement enforceable by law (s.2(h)). Essentials include competent parties, lawful consideration and object, and free consent. Breach typically yields compensation under sections 73–74. Specific performance may be available under the Specific Relief Act, 1963. Consumer and employment statutes may overlay special protections.",
    topics: "contract,breach,consideration,damages",
    tags: "contract act,agreements",
    jurisdiction: "IN",
    locale: "en",
    enactedYear: 1872,
    source: "Acts of Parliament (educational abridgement)",
  },
  {
    id: "in-ida",
    kind: "STATUTE",
    title: "Industrial Disputes Act, 1947",
    citation: "IDA, 1947",
    summary: "Framework for investigation and settlement of industrial disputes, conciliation, labour courts, and protections around retrenchment in covered establishments.",
    body: "The IDA channels collective employment conflict. Definitions of “workman” and “industry” matter. Conciliation precedes adjudication. Lay-off, retrenchment and closure in larger establishments can require prior permission. Many States have local amendments; always check the State overlay and newer labour codes where notified.",
    topics: "employment,labour,retrenchment,conciliation",
    tags: "industrial disputes,workman",
    jurisdiction: "IN",
    locale: "en",
    enactedYear: 1947,
    source: "Acts of Parliament (educational abridgement)",
  },
  {
    id: "us-const",
    kind: "CONSTITUTION",
    title: "Constitution of the United States",
    citation: "U.S. Const. (1787)",
    summary: "Creates a federal republic with separated powers, enumerated congressional powers, and a Bill of Rights added in 1791.",
    body: "The U.S. Constitution is short, entrenched, and interpreted heavily through judicial review (Marbury v. Madison). Articles I–III separate legislative, executive, and judicial power. Federalism splits authority with the States. Amendments require super-majorities. Later reconstruction and progressive amendments reshaped citizenship, suffrage, and due process.",
    topics: "constitution,federalism,separation of powers",
    tags: "united states,supreme law",
    jurisdiction: "US",
    locale: "en",
    enactedYear: 1787,
    source: "U.S. Constitution (public domain)",
  },
  {
    id: "us-1st",
    kind: "AMENDMENT",
    title: "First Amendment — Speech, press, religion, assembly",
    citation: "U.S. Const. amend. I",
    articleRef: "Amend. I",
    parentId: "us-const",
    summary: "Congress shall make no law respecting an establishment of religion, or abridging freedom of speech, press, assembly, or petition.",
    body: "The First Amendment constrains government, not private employers, with important caveats in public-function and state-action cases. Speech doctrine distinguishes content-based restrictions (strict scrutiny) from time-place-manner rules. Defamation, true threats, and some commercial speech are treated differently. Religion clauses cover establishment and free exercise.",
    topics: "speech,religion,press,assembly",
    tags: "first amendment,bill of rights",
    jurisdiction: "US",
    locale: "en",
    enactedYear: 1791,
    source: "U.S. Constitution",
  },
  {
    id: "us-14th",
    kind: "AMENDMENT",
    title: "Fourteenth Amendment — Due process and equal protection",
    citation: "U.S. Const. amend. XIV",
    articleRef: "Amend. XIV",
    parentId: "us-const",
    summary: "No State shall deprive any person of life, liberty, or property without due process, nor deny equal protection of the laws.",
    body: "Section 1 of the Fourteenth Amendment is the gateway for applying many Bill of Rights guarantees to the States (incorporation). Equal protection reviews classifications with different levels of scrutiny. Due process has procedural and substantive strands. Citizenship sentence overruled Dred Scott. Later statutes (e.g. civil rights acts) implement these guarantees.",
    topics: "due process,equal protection,citizenship,states",
    tags: "fourteenth amendment,reconstruction",
    jurisdiction: "US",
    locale: "en",
    enactedYear: 1868,
    source: "U.S. Constitution",
  },
  {
    id: "us-title-vii",
    kind: "STATUTE",
    title: "Title VII of the Civil Rights Act of 1964",
    citation: "42 U.S.C. § 2000e et seq.",
    summary: "Federal statute prohibiting employment discrimination because of race, color, religion, sex, or national origin (with later pregnancy and related interpretations).",
    body: "Title VII covers covered employers and provides administrative exhaustion before the EEOC in typical private-sector cases. Disparate treatment and disparate impact are distinct theories. Remedies can include back pay and injunctive relief. State fair-employment laws may be broader. This is a statute, not a constitutional claim, though the Fourteenth Amendment inspired it.",
    topics: "employment,discrimination,civil rights",
    tags: "title vii,eeoc",
    jurisdiction: "US",
    locale: "en",
    enactedYear: 1964,
    source: "U.S. Code (educational abridgement)",
  },
  {
    id: "gb-hra",
    kind: "STATUTE",
    title: "Human Rights Act 1998",
    citation: "HRA 1998 (UK)",
    summary: "Gives further effect in UK law to rights in the European Convention on Human Rights, including interpretation and declarations of incompatibility.",
    body: "The United Kingdom has no single codified constitution. The HRA requires courts to interpret legislation compatibly with Convention rights so far as possible (s.3) and allows declarations of incompatibility (s.4) without striking down primary legislation. Public authorities must not act incompatibly with Convention rights (s.6). Researching “UK constitution” should include this Act, Magna Carta principles, and parliamentary sovereignty.",
    topics: "human rights,constitution,ECHR,parliamentary sovereignty",
    tags: "HRA,UK,convention rights",
    jurisdiction: "GB",
    locale: "en",
    enactedYear: 1998,
    source: "UK statutes (educational abridgement)",
  },
  {
    id: "gb-magna",
    kind: "PRIMER",
    title: "Constitutional idea of Magna Carta (1215) in modern UK law",
    citation: "Magna Carta 1215 / 1297 (selected chapters)",
    summary: "Historic charter associated with lawful judgment and limits on arbitrary power; later chapters still cited symbolically and in legal history.",
    body: "Magna Carta is not a modern bill of rights, but chapter 29 (1297 confirmation) ideas — lawful judgment of peers and the law of the land — echo in due-process thinking. Most original chapters are spent. Use it as historical context when explaining the uncodified UK constitution, not as a standalone cause of action.",
    topics: "constitution,history,due process",
    tags: "magna carta,UK",
    jurisdiction: "GB",
    locale: "en",
    enactedYear: 1215,
    source: "Historical constitutional document (educational)",
  },
  {
    id: "fr-const",
    kind: "CONSTITUTION",
    title: "Constitution de la République française (1958)",
    citation: "Const. 4 oct. 1958",
    summary: "La Constitution de la Ve République organise les pouvoirs publics, le Conseil constitutionnel, et renvoie au Préambule de 1946 et à la Déclaration de 1789.",
    body: "Le bloc de constitutionnalité français comprend le texte de 1958, la DDHC de 1789, le Préambule de 1946 et la Charte de l’environnement. Le Conseil constitutionnel contrôle la conformité des lois. La QPC permet un contrôle a posteriori. Les libertés s’interprètent aussi à la lumière de la CEDH.",
    topics: "constitution,droits,conseil constitutionnel",
    tags: "Ve République,QPC",
    jurisdiction: "FR",
    locale: "fr",
    enactedYear: 1958,
    source: "Constitution française (abrégé pédagogique)",
  },
  {
    id: "fr-ddhc",
    kind: "CONSTITUTION",
    title: "Déclaration des droits de l’homme et du citoyen (1789)",
    citation: "DDHC 1789",
    parentId: "fr-const",
    summary: "Texte fondateur des droits : liberté, propriété, sûreté, résistance à l’oppression, et principe de légalité des délits et des peines.",
    body: "La DDHC affirme que les hommes naissent et demeurent libres et égaux en droits (art. 1er). La liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui (art. 4). Nul ne peut être accusé qu’en vertu d’une loi antérieure (art. 8). Elle a valeur constitutionnelle en France contemporaine via le Préambule de 1958.",
    topics: "droits,liberté,égalité,légalité pénale",
    tags: "DDHC,1789",
    jurisdiction: "FR",
    locale: "fr",
    enactedYear: 1789,
    source: "DDHC (domaine public)",
  },
  {
    id: "de-gg",
    kind: "CONSTITUTION",
    title: "Grundgesetz für die Bundesrepublik Deutschland",
    citation: "GG 1949",
    summary: "Das Grundgesetz schützt die Würde des Menschen (Art. 1) und bindet Gesetzgebung, vollziehende Gewalt und Rechtsprechung an die Grundrechte.",
    body: "Artikel 1 GG erklärt die Würde des Menschen für unantastbar. Die nachfolgenden Grundrechte binden alle staatliche Gewalt als unmittelbar geltendes Recht. Verfassungsänderungen sind durch die Ewigkeitsgarantie (Art. 79 Abs. 3) begrenzt. Das Bundesverfassungsgericht wacht über die Einhaltung. Für Nutzer in Deutschland beginnt die Recherche oft bei Art. 1–19 GG.",
    topics: "menschenwürde,grundrechte,bundesverfassungsgericht",
    tags: "grundgesetz,art 1",
    jurisdiction: "DE",
    locale: "de",
    enactedYear: 1949,
    source: "Grundgesetz (pädagogische Kurzfassung)",
  },
  {
    id: "de-art1",
    kind: "CONSTITUTION",
    title: "Artikel 1 GG — Menschenwürde",
    citation: "GG Art. 1",
    articleRef: "Art. 1 GG",
    parentId: "de-gg",
    summary: "Die Würde des Menschen ist unantastbar. Sie zu achten und zu schützen ist Verpflichtung aller staatlichen Gewalt.",
    body: "Art. 1 Abs. 1 GG ist die Leitnorm der deutschen Verfassungsordnung. Abs. 3 macht die Grundrechte unmittelbar geltendes Recht. Einfache Gesetze müssen verfassungskonform ausgelegt werden. Eingriffe in Freiheit und Gleichheit bedürfen einer gesetzlichen Grundlage und der Verhältnismäßigkeit.",
    topics: "würde,grundrechte,verhältnismäßigkeit",
    tags: "artikel 1,gg",
    jurisdiction: "DE",
    locale: "de",
    enactedYear: 1949,
    source: "Grundgesetz",
  },
  {
    id: "ca-charter",
    kind: "CONSTITUTION",
    title: "Canadian Charter of Rights and Freedoms",
    citation: "Constitution Act, 1982, Part I",
    summary: "Entrenched rights including expression, equality, and legal rights, subject to reasonable limits under section 1 and the notwithstanding clause in section 33.",
    body: "The Charter binds government action. Section 1 permits reasonable limits prescribed by law that are demonstrably justified. Equality (s.15) and legal rights (ss.7–14) are frequent litigation grounds. Section 24 provides remedies; s.52 makes inconsistent laws of no force or effect. Quebec civil law coexists with federal criminal law.",
    topics: "charter,equality,expression,reasonable limits",
    tags: "canada,section 1,section 15",
    jurisdiction: "CA",
    locale: "en",
    enactedYear: 1982,
    source: "Constitution Act, 1982 (educational abridgement)",
  },
  {
    id: "au-const",
    kind: "CONSTITUTION",
    title: "Commonwealth of Australia Constitution Act",
    citation: "Australian Constitution (1901)",
    summary: "Federal constitution distributing powers between Commonwealth and States, with implied freedom of political communication developed by the High Court.",
    body: "Australia’s Constitution is a statute of the UK Parliament that became the local supreme law. Chapter III courts, s.51 heads of power, and s.109 inconsistency are core. There is no comprehensive bill of rights at federal level; rights are scattered and implied. Amendments require a referendum (s.128).",
    topics: "federalism,referendum,high court",
    tags: "australia,constitution",
    jurisdiction: "AU",
    locale: "en",
    enactedYear: 1901,
    source: "Australian Constitution (educational abridgement)",
  },
  {
    id: "sg-const",
    kind: "CONSTITUTION",
    title: "Constitution of the Republic of Singapore",
    citation: "Singapore Constitution",
    summary: "Supreme law of Singapore, including Part IV fundamental liberties (life, liberty, speech, religion, equality) subject to parliamentary restrictions.",
    body: "Article 4 declares the Constitution supreme. Article 9 protects life and liberty; Article 12 equality; Article 14 speech, assembly and association subject to restrictions Parliament considers necessary. The legal system is common-law based with a strong parliamentary role. Always check the latest revised edition.",
    topics: "fundamental liberties,supremacy,speech",
    tags: "singapore,article 9,article 14",
    jurisdiction: "SG",
    locale: "en",
    enactedYear: 1965,
    source: "Singapore Constitution (educational abridgement)",
  },
  {
    id: "za-const",
    kind: "CONSTITUTION",
    title: "Constitution of the Republic of South Africa, 1996",
    citation: "S. Afr. Const., 1996",
    summary: "Transformative constitution with a justiciable Bill of Rights, including socio-economic rights, enforced by the Constitutional Court.",
    body: "Section 7 affirms the Bill of Rights as a cornerstone of democracy. Section 36 is a general limitations clause. Socio-economic rights (housing, health, food) are progressively realisable. Section 39 requires interpretation that promotes the values of an open and democratic society and may consider international law. Apartheid-era law is subject to constitutional supremacy (s.2).",
    topics: "bill of rights,socio-economic rights,limitations",
    tags: "south africa,section 36",
    jurisdiction: "ZA",
    locale: "en",
    enactedYear: 1996,
    source: "South African Constitution (educational abridgement)",
  },
  {
    id: "ae-primer",
    kind: "PRIMER",
    title: "UAE legal system primer — federal civil law and personal status",
    citation: "UAE Federal Constitution 1971 (primer)",
    summary: "The UAE is a federation of emirates with a written constitution, civil-law codes, and personal-status rules that can differ by religion and emirate-level courts.",
    body: "Start with the Federal Constitution (1971), then the relevant federal code (civil transactions, commercial, labour, penal). Free-zone courts (DIFC, ADGM) apply common-law style rules for many commercial disputes. Family and personal-status matters may follow different codes. Always identify whether the forum is onshore or a free zone.",
    topics: "federalism,civil law,free zones,personal status",
    tags: "UAE,DIFC,constitution",
    jurisdiction: "AE",
    locale: "en",
    enactedYear: 1971,
    source: "Educational primer",
  },
  {
    id: "intl-udhr",
    kind: "TREATY",
    title: "Universal Declaration of Human Rights",
    citation: "UDHR (1948)",
    summary: "UN General Assembly declaration of inherent rights — not a treaty by itself, but the foundation of later covenants and many constitutions.",
    body: "The UDHR articulates dignity, equality, fair trial, and socio-economic rights. It is not directly enforceable in every domestic court, but courts and constitutions frequently cite it. Binding cousins include the ICCPR and ICESCR. Use UDHR as a comparative lens, then descend into the user’s national constitution and statutes.",
    topics: "human rights,dignity,international law",
    tags: "UN,UDHR",
    jurisdiction: "INTL",
    locale: "en",
    enactedYear: 1948,
    source: "United Nations (public domain)",
  },
  {
    id: "intl-iccpr",
    kind: "TREATY",
    title: "International Covenant on Civil and Political Rights",
    citation: "ICCPR (1966)",
    parentId: "intl-udhr",
    summary: "Binding treaty on civil and political rights: life, liberty, fair trial, expression, and equality, with a Human Rights Committee.",
    body: "States parties must respect and ensure Covenant rights. Article 14 fair-trial guarantees and Article 19 expression are frequently invoked. Domestic effect depends on whether the State is dualist or monist and on implementing legislation. Reservations may limit particular articles. Pair research with the user’s constitution.",
    topics: "civil rights,fair trial,expression,treaty",
    tags: "ICCPR,human rights committee",
    jurisdiction: "INTL",
    locale: "en",
    enactedYear: 1966,
    source: "United Nations (educational abridgement)",
  },
  {
    id: "es-primer-in",
    kind: "PRIMER",
    title: "Cómo leer una constitución: derechos, límites y reformas",
    citation: "LegalAid primer",
    summary: "Guía en español para entender constituciones, enmiendas y leyes ordinarias según el país seleccionado.",
    body: "Una constitución es la norma suprema. Las enmiendas cambian esa norma con un procedimiento agravado. Las leyes ordinarias no pueden contradecirla. Cuando busque un tema (por ejemplo, “igualdad” o “despido”), filtre por país y lea: (1) cláusula constitucional, (2) enmiendas posteriores, (3) ley de desarrollo, (4) un caso líder. LegalAid clasifica esos cuatro capas.",
    topics: "constitución,enmiendas,método de investigación",
    tags: "primer,español",
    jurisdiction: "INTL",
    locale: "es",
    enactedYear: 2024,
    source: "LegalAid educational primer",
  },
  {
    id: "in-kesavananda",
    kind: "CASE_NOTE",
    title: "Kesavananda Bharati v. State of Kerala (basic structure)",
    citation: "(1973) 4 SCC 225",
    summary: "Supreme Court of India held that Parliament’s amending power cannot destroy the Constitution’s basic structure.",
    body: "The majority recognised that Article 368 is wide but not unlimited. Features such as supremacy of the Constitution, democracy, secularism, and judicial review have been treated as basic (the list is judicial, not exhaustive). When a user asks whether an Indian amendment is valid, the basic-structure doctrine is the first analytical filter after the Article 368 procedure.",
    topics: "amendment,basic structure,judicial review",
    tags: "kesavananda,supreme court",
    jurisdiction: "IN",
    locale: "en",
    enactedYear: 1973,
    source: "Case note (educational)",
  },
];
